"""empty message

Revision ID: b09a2eb6369d
Revises: 2b7380507a71
Create Date: 2023-03-02 15:58:18.285785

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b09a2eb6369d"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_full", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "dummy_model", "name", existing_type=mysql.VARCHAR(length=200), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dummy_model", "name", existing_type=mysql.VARCHAR(length=200), nullable=True
    )
    op.drop_table("team_model")
    # ### end Alembic commands ###
